Pushed install and script logic to DI switch blocks.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -17,84 +17,30 @@ env:
     #
     - TEST_OVER_DI=false
     
-    # Nope -- no logic witin the env segment
-#    - |
-#        if [ ! -z ${TEST_OVER_DI} ] && [ ${TEST_OVER_DI} == true ]; then
-#            #
-#            SUDO_VAL=required
-#            #
-#        else
-#            SUDO_VAL=false
-#        fi
-# OK, just manually set the value
+    # Aside -- boolean sub logic / assignment processing does NOT appear
+    # to work on items within the env segment.
+    
+    # ...so, just manually set the sudo value (options false, required, true)
     - SUDO_VAL=false
     
     # could space delimiters work here IMI
-#    - SERVICES_VAL="docker"
+    # - SERVICES_VAL="docker"
     
+# the sudo services combination appears to invoke a start for each item rendered
+# That said -- it does NOT appear to be required for the direct run over 
+# docker image use-case (infact it may well be already running in the background)
+#
 sudo:   ${SUDO_VAL}
-# I wonder -- can sudo and services definitions get managed
-# by the same logic block (rather than logic blocks within) IMI
-#
-#sudo: required
-# This stub renders  "unrecognized service" -- try it embedded next
-#sudo: |
-#    if [ ! -z ${TEST_OVER_DI} ] && [ ${TEST_OVER_DI} == true ]; then
-#        #
-#        required
-#        #
-#    else
-#        false
-#    fi
 
+# Logical management of Sudo and services definitions does NOT appear to work.
+# Moreover, services were NOT defined in the original logic, and it does NOT
+# appear to be a requirement for our DI run use-case, so leave it out.
+#
 #services:
-##    - docker
-#    - |
-#        if [ ! -z ${TEST_OVER_DI} ] && [ ${TEST_OVER_DI} == true ]; then
-#            #
-#            docker
-#            #
-#        else
-##            # N/A -- no services reference.
-#        fi
+#    - docker
 
-# BLa bla
-services:   ${SERVICES_VAL}
-
-# Ok that munged up sudo service references, how about together IMI
-# No joy -- pushing this out appears to cause Travis to ignore it
-#|
-#    if [ ! -z ${TEST_OVER_DI} ] && [ ${TEST_OVER_DI} == true ]; then
-#
-#        sudo: required
-#        
-#        services:
-#            - docker#
-#
-#    else
-#        # No sudo, no services.
-#        sudo: false
-#    fi
-    
-# What if we add that segment to before_install IMI
-    
+   
 before_install:
-    # added sudo and services here YES IMI
-#    # No joy -- citing sudo here as a sub reference flags sudo:: command not found failure DOhttt!
-#    - |
-#        if [ ! -z ${TEST_OVER_DI} ] && [ ${TEST_OVER_DI} == true ]; then
-#
-#            sudo: required
-#            
-#            services:
-#                - docker
-#
-#        else
-#            # No sudo, no services.
-#            sudo: false
-#        fi
-    
-    
     # Use the YAML pipe to process over multi-line entries
     # << https://stackoverflow.com/questions/38789253/running-script-conditionally-does-not-work-in-travis-yml-why
     # This works -- Read defined (not zero) and eq true, else not
@@ -123,27 +69,31 @@ before_install:
 # Note:  if No language references defined, system defaults to Ruby -- let the python ref remain.
 # (even though unused if execution occurs down in docker level)
 language: python
+
 python:
-  - "3.6"
+    - "3.6"
 
 install:
     # Pulling in docker image without || true -- want it to fail if not there.
-    - export BBNQConda_DI="merlinbeast/bbnq:bbnqconda_centos7_4_bbnq_pylib_v1.0.1_19.12.2018"
+#    - export BBNQConda_DI="merlinbeast/bbnq:bbnqconda_centos7_4_bbnq_pylib_v1.0.1_19.12.2018"
     
-    # Sample logic to see if we can determine pull needs or not
-    # Sadly -- this did NOT work as expected (as it does under normal shells)
-    # Could this be that we don't have a complete linux system here, currently,
-    # and still need to explode out a base linux environment for Travis IMI
-#    - export TGT_DI=`docker images | grep ${BBNQConda_DI}`
-#    - echo ''; if [ -z "${BBNQConda_DI}" ]; then echo "Docker cache missed -- ${BBNQConda_DI} pull pending..." ; docker pull ${BBNQConda_DI}; else echo "Docker cache hit -- ${BBNQConda_DI} docked and ready..."; fi
-    # test the image display -- anything IMI -- Nope  docker cache appears empty
-    # upon entry -- hence dynamic load logic pointless; just load it
-    #- docker images
     
-#    - echo "Pulling in BBNQConda docker image via ~:"
-##    - docker pull merlinbeast/bbnq:bbnqconda_centos7_4_bbnq_pylib_v1.0.1_19.12.2018
+    # Sample logic to determine if we need to pull an image or not does 
+    # NOT appear to work as the docker images call returns empty set after 
+    # initialization.
+    # - docker images
+    
     # Popping constant pull back in
-    - docker pull ${BBNQConda_DI}
+#    - docker pull ${BBNQConda_DI}
+
+    # Defining pip install commands for use in the docker session
+    # Note -- script test was using direct clone, then walking the installation
+    # to do pip install, documentation rendereing and such.
+    #
+    # Define dependent/sibling repository modules to PiP load prior to testing.
+#    - export TGT_PIPLOADS="pip install git+https://github.com/BBN-Q/Adapt.git; echo ''; echo '# ---'; pip install git+https://github.com/BBN-Q/QGL.git"
+    # the utf8 settings are required for documentation rendering logic.
+#    - export DI_ENV_VALS="-e BBN_MEAS_FILE=test/test_measure.yml -e LC_ALL=en_US.utf8 -e LANG=en_US.utf8"
     
   # Setup anaconda. See http://conda.pydata.org/docs/travis.html
 
@@ -169,14 +119,58 @@ install:
 #  - conda install -c ecpy atom;
 #  - export PYTHONPATH=$PYTHONPATH:$PWD/src
 
-    # Defining pip install commands for use in the docker session
-    # Note -- script test was using direct clone, then walking the installation
-    # to do pip install, documentation rendereing and such.
-    #
-    # Define dependent/sibling repository modules to PiP load prior to testing.
-    - export TGT_PIPLOADS="pip install git+https://github.com/BBN-Q/Adapt.git; echo ''; echo '# ---'; pip install git+https://github.com/BBN-Q/QGL.git"
-    # the utf8 settings are required for documentation rendering logic.
-    - export DI_ENV_VALS="-e BBN_MEAS_FILE=test/test_measure.yml -e LC_ALL=en_US.utf8 -e LANG=en_US.utf8"
+# Pull in the install switch logic:
+    - |
+        if [ ! -z ${TEST_OVER_DI} ] && [ ${TEST_OVER_DI} == true ]; then
+            
+            # Pulling in docker image without || true -- want it to fail if not there.
+            - export BBNQConda_DI="merlinbeast/bbnq:bbnqconda_centos7_4_bbnq_pylib_v1.0.1_19.12.2018"
+            
+            
+            # Sample logic to determine if we need to pull an image or not does 
+            # NOT appear to work as the docker images call returns empty set after 
+            # initialization.
+            # - docker images
+            
+            # Popping constant pull back in
+            - docker pull ${BBNQConda_DI}
+
+            # Defining pip install commands for use in the docker session
+            # Note -- script test was using direct clone, then walking the installation
+            # to do pip install, documentation rendereing and such.
+            #
+            # Define dependent/sibling repository modules to PiP load prior to testing.
+            - export TGT_PIPLOADS="pip install git+https://github.com/BBN-Q/Adapt.git; echo ''; echo '# ---'; pip install git+https://github.com/BBN-Q/QGL.git"
+            # the utf8 settings are required for documentation rendering logic.
+            - export DI_ENV_VALS="-e BBN_MEAS_FILE=test/test_measure.yml -e LC_ALL=en_US.utf8 -e LANG=en_US.utf8"
+
+        else
+        
+            # Original sestup logic here
+            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
+            bash miniconda.sh -b -p $HOME/miniconda
+            export PATH="$HOME/miniconda/bin:$PATH"
+            export BBN_MEAS_FILE="$PWD/test/test_measure.yml"
+            echo "Measure file at $BBN_MEAS_FILE"
+            hash -r
+            conda config --set always_yes yes --set changeps1 no
+            conda update -q conda
+            Useful for debugging any issues with conda
+            conda info -a
+
+            # Create conda environment with dependencies
+            conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib h5py pandas networkx cffi bokeh jupyter future psutil
+            source activate test-environment
+            export GIT_LFS_SKIP_SMUDGE=1
+            pip install git+https://github.com/BBN-Q/Adapt.git
+            pip install git+https://github.com/BBN-Q/QGL.git
+            pip install tqdm pyvisa coveralls ruamel.yaml watchdog scikit-learn pyusb
+            export GIT_LFS_SKIP_SMUDGE=0
+            conda install -c ecpy atom;
+            export PYTHONPATH=$PYTHONPATH:$PWD/src
+            
+        fi
+
     
 script:
 #  - coverage run -m unittest discover -v test
@@ -201,7 +195,22 @@ script:
 #    - docker run -v $PWD:/root/RepoCDir ${DI_ENV_VALS} ${BBNQConda_DI} /bin/sh -c "source ~/.bashrc; echo ''; echo '# --- DI Run-Time info:'; python --version; echo ''; conda info; conda list; echo ''; echo '# --- PIP loading dependency mods...'; ${TGT_PIPLOADS}; cd ~/RepoCDir; pwd; echo ''; echo '# --- Pip Installing repo clone...'; pip install -e .; echo ''; echo '# --- Unittest begin...'; python -m unittest discover -v test"
 #    - docker run -v $PWD:/root/RepoCDir ${DI_ENV_VALS} ${BBNQConda_DI} /bin/sh -c "source ~/.bashrc; echo ''; echo '# --- DI Run-Time info:'; python --version; echo ''; conda info; conda list; echo ''; echo '# --- PIP loading dependency mods...'; ${TGT_PIPLOADS}; cd ~/RepoCDir; echo ''; echo '# --- Pip Installing repo clone...'; pwd; pip install -e .; echo ''; echo '# --- Unittest begin...'; python -m unittest discover -v test"
 # log text refinement five   
-    - docker run -v $PWD:/root/RepoCDir ${DI_ENV_VALS} ${BBNQConda_DI} /bin/sh -c "source ~/.bashrc; echo ''; echo '# --- DI Run-Time info:'; python --version; conda info; conda list; echo ''; echo '# --- PIP loading dependency mods...'; ${TGT_PIPLOADS}; cd ~/RepoCDir; echo ''; echo '# --- Pip Installing repo clone...'; pwd; pip install -e .; echo ''; echo '# --- Unittest begin...'; python -m unittest discover -v test"
+# 
+# Commented out working invocation for switch logic, below
+#    - docker run -v $PWD:/root/RepoCDir ${DI_ENV_VALS} ${BBNQConda_DI} /bin/sh -c "source ~/.bashrc; echo ''; echo '# --- DI Run-Time info:'; python --version; conda info; conda list; echo ''; echo '# --- PIP loading dependency mods...'; ${TGT_PIPLOADS}; cd ~/RepoCDir; echo ''; echo '# --- Pip Installing repo clone...'; pwd; pip install -e .; echo ''; echo '# --- Unittest begin...'; python -m unittest discover -v test"
+
+# Pull in the script switch logic:
+    - |
+        if [ ! -z ${TEST_OVER_DI} ] && [ ${TEST_OVER_DI} == true ]; then
+            
+            docker run -v $PWD:/root/RepoCDir ${DI_ENV_VALS} ${BBNQConda_DI} /bin/sh -c "source ~/.bashrc; echo ''; echo '# --- DI Run-Time info:'; python --version; conda info; conda list; echo ''; echo '# --- PIP loading dependency mods...'; ${TGT_PIPLOADS}; cd ~/RepoCDir; echo ''; echo '# --- Pip Installing repo clone...'; pwd; pip install -e .; echo ''; echo '# --- Unittest begin...'; python -m unittest discover -v test"
+
+        else
+        
+            # Original sestup logic here
+            coverage run -m unittest discover -v test
+
+        fi
     
     
 after_script:
@@ -214,4 +223,4 @@ after_script:
 cache:
   directories:
     - $HOME/download
-#    - $HOME/.cache/pip
+    - $HOME/.cache/pip
