Attempt docs build in single workflow

diff --git a/.github/workflows/actions-test.yml b/.github/workflows/actions-test.yml
--- a/.github/workflows/actions-test.yml
+++ b/.github/workflows/actions-test.yml
@@ -21,6 +21,7 @@ jobs:
     - name: Install dependencies
       run: |
         conda install -yq numpy scipy h5py sphinx matplotlib pandas networkx cffi jupyter psutil sqlalchemy ipykernel ipywidgets
+        pip install recommonmark sphinx-rtd-theme nbsphinx mkdocs markdown commonmark
         export GIT_LFS_SKIP_SMUDGE=1
         pip install git+https://github.com/BBN-Q/bbndb.git
         pip install git+https://github.com/BBN-Q/QGL.git@develop
@@ -31,3 +32,32 @@ jobs:
       run: |
         pip install -e .
         python -m unittest discover -v test
+    - name: Sphinx Build
+      # You may pin to the exact commit or the version.
+      # uses: ammaraskar/sphinx-action@8b4f60114d7fd1faeba1a712269168508d4750d2
+      uses: ammaraskar/sphinx-action@0.4
+      with:
+        # The folder containing your sphinx docs.
+        docs-folder: docs
+        # The command used to build your documentation.
+        build-command: make html
+        # Run before the build command, you can use this to install system level dependencies, for example with "apt-get update -y && apt-get install -y perl"
+        pre-build-command: pip install -e .
+    - name: Commit documentation changes
+      run: |
+        #git clone https://github.com/grahamrow/auspex.git --branch gh-pages --single-branch gh-pages
+        git checkout gh-pages
+        cp -r docs/_build/html/* gh-pages/
+        cd gh-pages
+        git config --local user.email "action@github.com"
+        git config --local user.name "GitHub Action"
+        git add .
+        git commit -m "Update documentation" -a || true
+        # The above command will fail if no changes were present, so we ignore
+        # the return code.
+    - name: Push changes
+      uses: ad-m/github-push-action@master
+      with:
+        branch: gh-pages
+        directory: gh-pages
+        github_token: ${{ secrets.GITHUB_TOKEN }}
